config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :groups
  resources :payments

  unauthenticated do
    root "users#welcome"
  end

  root 'groups#index', as: "categories"

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payment_groups, dependent: :destroy

  validates :name, :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :payment_groups, dependent: :destroy

  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/payment_group.rb
class PaymentGroup < ApplicationRecord
  belongs_to :payment
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :payments

  validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @payments_group = @group.payment_groups.order('created_at DESC')
  end

  # GET /groups/new
  def new
    @group = Group.new
    @icons = ['img1.png', 'img2.png', 'img3.png', 'img4.png', 'img5.png']
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/payment_groups_controller.rb
class PaymentGroupsController < ApplicationController
  before_action :set_payment_group, only: %i[show edit update destroy]

  # GET /payment_groups or /payment_groups.json
  def index
    @payment_groups = PaymentGroup.all
  end

  # GET /payment_groups/1 or /payment_groups/1.json
  def show; end

  # GET /payment_groups/new
  def new
    @payment_group = PaymentGroup.new
  end

  # GET /payment_groups/1/edit
  def edit; end

  # POST /payment_groups or /payment_groups.json
  def create
    @payment_group = PaymentGroup.new(payment_group_params)

    respond_to do |format|
      if @payment_group.save
        format.html { redirect_to payment_group_url(@payment_group), notice: 'Payment group was successfully created.' }
        format.json { render :show, status: :created, location: @payment_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_groups/1 or /payment_groups/1.json
  def update
    respond_to do |format|
      if @payment_group.update(payment_group_params)
        format.html { redirect_to payment_group_url(@payment_group), notice: 'Payment group was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_groups/1 or /payment_groups/1.json
  def destroy
    @payment_group.destroy

    respond_to do |format|
      format.html { redirect_to payment_groups_url, notice: 'Payment group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment_group
    @payment_group = PaymentGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_group_params
    params.require(:payment_group).permit(:payment_id, :group_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # POST /payments or /payments.json
  def create
    params = payment_params
    @payment = Payment.new(name: params[:name], amount: params[:amount])
    @payment.user_id = current_user.id

    respond_to do |format|
      if @payment.save
        @categories_ids = params[:categories]
        @categories_ids.each do |element|
          next if element == ''

          payment_group = PaymentGroup.new(group_id: element.to_i)
          payment_group.payment = @payment
          payment_group.save
        end
        format.html { redirect_to groups_url, notice: 'Payment was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, categories: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/payment_groups_helper.rb
module PaymentGroupsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class="categories-container">
<div class="menu">
<ul>
  <li><%= button_to "Log out", destroy_user_session_path, :method => :delete %></li>
</ul>
  </div>
  <div class="categories-header">
    <i class="fas fa-bars fa-2x"></i>
    <h2>CATEGORIES</h2>
  </div>

  <% if notice %>
    <p style="color: green"><%= notice %></p>
  <% end %>

  <div class="groups">
    <% @groups.each do |group| %>
      <a class="group-container" href="groups/<%= group.id %>">
        <div>
          <%=image_tag "#{group.icon}"%>
          <p><%= group.name %> <br> <span class="time"><%= Date.strptime(group.created_at.to_datetime.to_s).strftime("%d/%m/%Y") %> </span></p>
        </div>
        <% total_amount = 0.00 %>
        <% group.payment_groups.each do |element| %>
          <% total_amount += element.payment.amount %>
        <% end %>
        <p>$<%= total_amount %></p>
      </a>
    <% end %>
  </div>

  <%= link_to "Add a new category", new_group_path, class: "create-new-category" %>
</div>

app/views/groups/new.html.erb
<%= form_with(model: @group, html: {class: "new-group-form"}) do |form| %>
  <div class="new-group-header">
    <a href="/"><i class="fas fa-arrow-left fa-2x"></i></a>
    <h2>NEW CATEGORY</h2>
    <div class="actions">
      <%= form.submit "Create" %>
    </div>
  </div>

  <% if @group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name", required: true %>
  </div>

  <div>
    <%= form.select :icon, options_for_select([
        ['Shopping' ,@icons[0]],
        ['Education' ,@icons[1]],
        ['Bills' ,@icons[2]],
        ['Insurance' ,@icons[3]],
        ['Travel' ,@icons[4]],
      ]),{ include_blank: "Select Icon"}, required: true , class:"icon-select"%>
  </div>

<% end %>

app/views/groups/show.html.erb
<div class="transactions-container">
  <div class="transactions-header">
    <a href="/"><i class="fas fa-arrow-left fa-2x"></i></a>
    <h2>TRANSACTIONS</h2>
  </div>

  <% if notice %>
    <p style="color: green"><%= notice %></p>
  <% end %>

  <div class="transactions-inner-container">
    <div class="group-container">
      <div>
        <%=image_tag "#{@group.icon}"%>
        <p><%= @group.name %> <br> <span class="time"><%= Date.strptime(@group.created_at.to_datetime.to_s).strftime("%d/%m/%Y") %> </span></p>
      </div>
      <% total_amount = 0.00 %>
      <% @group.payment_groups.each do |element| %>
        <% total_amount += element.payment.amount %>
      <% end %>
      <p>Total: $<%= total_amount %></p>
      <%= button_to "Delete", group_path(@group), :method => :delete %>
    </div>

    <h3>Transactions</h3>
    
    <div class="payments-container">
      <% @payments_group.each do |element|%>
        <div class="payment">
          <p><%= element.payment.name %> <br> <span class="time"><%= Date.strptime(element.payment.created_at.to_datetime.to_s).strftime("%d/%m/%Y") %></span> </p>
          <p>$<%= element.payment.amount %></p>
          <%= button_to "Delete", payment_path(element.payment), :method => :delete %>
        </div>
      <% end %>
    </div>
  </div>

  <%= link_to "Add a new transaction", new_payment_path, class: "create-new-transaction" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta property="og:image" content="https://raw.githubusercontent.com/ShahierNashaat/budget-app/dev/app/assets/images/Screenshot.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/a3ad5bee92.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_groups/_form.html.erb
<%= form_with(model: payment_group) do |form| %>
  <% if payment_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment_group.errors.count, "error") %> prohibited this payment_group from being saved:</h2>

      <ul>
        <% payment_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :payment_id, style: "display: block" %>
    <%= form.text_field :payment_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_groups/_payment_group.html.erb
<div id="<%= dom_id payment_group %>">
  <p>
    <strong>Payment:</strong>
    <%= payment_group.payment_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= payment_group.group_id %>
  </p>

</div>

app/views/payment_groups/edit.html.erb
<h1>Editing payment group</h1>

<%= render "form", payment_group: @payment_group %>

<br>

<div>
  <%= link_to "Show this payment group", @payment_group %> |
  <%= link_to "Back to payment groups", payment_groups_path %>
</div>

app/views/payment_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payment groups</h1>

<div id="payment_groups">
  <% @payment_groups.each do |payment_group| %>
    <%= render payment_group %>
    <p>
      <%= link_to "Show this payment group", payment_group %>
    </p>
  <% end %>
</div>

<%= link_to "New payment group", new_payment_group_path %>

app/views/payment_groups/new.html.erb
<h1>New payment group</h1>

<%= render "form", payment_group: @payment_group %>

<br>

<div>
  <%= link_to "Back to payment groups", payment_groups_path %>
</div>

app/views/payment_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment_group %>

<div>
  <%= link_to "Edit this payment group", edit_payment_group_path(@payment_group) %> |
  <%= link_to "Back to payment groups", payment_groups_path %>

  <%= button_to "Destroy this payment group", @payment_group, method: :delete %>
</div>

app/views/payments/new.html.erb
<%= form_with(model: @payment, html: {class: "new-payment-form"}) do |form| %>
  <div class="new-payment-header">
    <a onclick="history.back()"><i class="fas fa-arrow-left fa-2x"></i></a>
    <h2>NEW CATEGORY</h2>
    <div class="actions">
      <%= form.submit "Create" %>
    </div>
  </div>
  
  <% if @payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% @payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Name", required: true  %>
  </div>

  <div class="field">
    <%= form.number_field :amount, placeholder: "Amount", required: true, step: 0.01  %>
  </div>

  <div>
    <%= form.select :categories, Group.where(user_id: current_user.id).collect {|g| [g.name, g.id]}, { include_blank: false }, required: true, class:"categories-select selectpicker", multiple: true %>
  </div>

<% end %>

<script>
  $('select').selectpicker();
  $('.filter-option-inner-inner').text('Select at least one category')
</script>

app/views/users/welcome.html.erb
<div class="welcome-container">

    <h1>Budget Saver</h1>

    <div class="links">
        <%= link_to "LOG IN", new_user_session_path %><br />
        <%= link_to "SIGN UP", new_user_registration_path %><br />
    </div>

</div>